set_property PACKAGE_PIN R2 [get_ports clk_in1_0]
set_property IOSTANDARD SSTL135 [get_ports clk_in1_0]
set_property PACKAGE_PIN V15 [get_ports {o_PC_0[3]}]
set_property PACKAGE_PIN U12 [get_ports {o_PC_0[2]}]
set_property PACKAGE_PIN V13 [get_ports {o_PC_0[1]}]
set_property PACKAGE_PIN T12 [get_ports {o_PC_0[0]}]
set_property PACKAGE_PIN V12 [get_ports i_Uart_Tx_In_0]
set_property IOSTANDARD LVCMOS33 [get_ports {o_PC_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_PC_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_PC_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_PC_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_Uart_Tx_In_0]
set_property PACKAGE_PIN V14 [get_ports ext_reset_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_in_0]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list computer_i/mig_7series_0/u_computer_mig_7series_0_0_mig/u_ddr3_infrastructure/u_bufg_clkdiv0_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {o_PC_0_OBUF[0]} {o_PC_0_OBUF[1]} {o_PC_0_OBUF[2]} {o_PC_0_OBUF[3]}]]
set_property IOSTANDARD LVCMOS33 [get_ports i_Uart_Tx_Out_0]
set_property PACKAGE_PIN R12 [get_ports i_Uart_Tx_Out_0]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_u_bufg_clkdiv0_0]
